/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.glass.events.KeyEvent;
import data.dao.DAOFactory;
import data.dto.MjestoPrebivalistaDTO;
import data.dto.PrijavaNaKonkursDTO;
import data.dto.StudentDTO;
import static forms.PregledPrijavaSkolskeGodineDialog.skolskaGodina;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class AzurirajPrijavuForm extends javax.swing.JFrame {

    /**
     * Creates new form AzurirajPrijavuForm
     */
    public AzurirajPrijavuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JMBField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        skolskaGodinaField = new javax.swing.JTextField();
        azurirajButton = new javax.swing.JToggleButton();
        prikaziSvePrijaveButton = new javax.swing.JButton();
        skolskaGodinaField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JMBField1 = new javax.swing.JTextField();
        prikaziPrijavuButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idPrijaveField = new javax.swing.JTextField();
        skolskaGodina3Field = new javax.swing.JTextField();
        azuriraj2Button = new javax.swing.JButton();
        otkaziButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ažuriraj prijavu");
        setMaximumSize(new java.awt.Dimension(335, 360));
        setMinimumSize(new java.awt.Dimension(335, 360));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                zatvaraj(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ažuriraj prijavu"));

        jLabel1.setText("JMB:");

        JMBField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JMBFieldKeyPressed(evt);
            }
        });

        jLabel2.setText("Školska godina:");

        skolskaGodinaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skolskaGodinaFieldActionPerformed(evt);
            }
        });
        skolskaGodinaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                skolskaGodinaFieldKeyPressed(evt);
            }
        });

        azurirajButton.setText("Ažuriraj");
        azurirajButton.setToolTipText("");
        azurirajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azurirajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(skolskaGodinaField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(JMBField))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(azurirajButton)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JMBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(skolskaGodinaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(azurirajButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        prikaziSvePrijaveButton.setText("Prikaži sve prijave školske godine");
        prikaziSvePrijaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziSvePrijaveButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Školska godina:");

        prikaziPrijavuButton.setText("Prikaži prijavu");
        prikaziPrijavuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziPrijavuButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("JMB:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Аžuriraj prijavu"));
        jPanel2.setToolTipText("");

        jLabel5.setText("Id prijave:");

        jLabel6.setText("Školska godina:");

        idPrijaveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPrijaveFieldActionPerformed(evt);
            }
        });

        azuriraj2Button.setText("Ažuriraj");
        azuriraj2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azuriraj2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(idPrijaveField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skolskaGodina3Field)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(azuriraj2Button)
                .addGap(136, 136, 136))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idPrijaveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(skolskaGodina3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(azuriraj2Button)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        otkaziButton.setText("Nazad");
        otkaziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otkaziButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prikaziSvePrijaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(skolskaGodinaField1))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prikaziPrijavuButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(61, 61, 61)
                                        .addComponent(JMBField1)))
                                .addGap(77, 77, 77))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otkaziButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(skolskaGodinaField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prikaziSvePrijaveButton)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JMBField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prikaziPrijavuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otkaziButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void azurirajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azurirajButtonActionPerformed
        String skolskaGodina = skolskaGodinaField.getText();
        String jmb = JMBField.getText();

        if (!skolskaGodina.matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greska u formatu skolske godine. Potreban format xxxx/yyyy.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (jmb.length() != 13) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greska pri unosu JMB.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StudentDTO student = DAOFactory.getDAOFactory().getStudentDAO().student(jmb);
        if (student == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Nepostojeci JMB.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PrijavaNaKonkursDTO prijava = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijava(jmb, skolskaGodina);
        if (prijava == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji takva prijava.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        MjestoPrebivalistaDTO mjesto = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().mjestoPrebivalista(prijava.getBrojPoste());

        new IzmijeniPrijavuDialog(this, true, jmb, skolskaGodina).setVisible(true);
    }//GEN-LAST:event_azurirajButtonActionPerformed

    private void otkaziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otkaziButtonActionPerformed
        dispose();
    }//GEN-LAST:event_otkaziButtonActionPerformed

    private void JMBFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JMBFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            azurirajButton.doClick();
        }
    }//GEN-LAST:event_JMBFieldKeyPressed

    private void skolskaGodinaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skolskaGodinaFieldActionPerformed

    }//GEN-LAST:event_skolskaGodinaFieldActionPerformed

    private void skolskaGodinaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_skolskaGodinaFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            azurirajButton.doClick();
        }
    }//GEN-LAST:event_skolskaGodinaFieldKeyPressed

    private void prikaziSvePrijaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziSvePrijaveButtonActionPerformed
        String skolskaGodinaa = skolskaGodinaField1.getText();

        if (!skolskaGodinaa.matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Pogresno unijeta skolska godina. Potreban format je xxxx/yyyy.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PregledPrijavaSkolskeGodineDialog novi = new PregledPrijavaSkolskeGodineDialog(this, true, skolskaGodinaa);
        novi.setVisible(true);

    }//GEN-LAST:event_prikaziSvePrijaveButtonActionPerformed

    private void prikaziPrijavuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziPrijavuButtonActionPerformed
        String skolskaGodinaa = skolskaGodinaField1.getText();

        if (!skolskaGodinaa.matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Pogresno unijeta skolska godina. Potreban format je xxxx/yyyy.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jmb = JMBField1.getText();
        if (jmb.length() != 13) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greska pri unosu JMB.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StudentDTO student = DAOFactory.getDAOFactory().getStudentDAO().student(jmb);
        if (student == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Nepostojeci JMB.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PrijavaNaKonkursDTO prijava = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijava(jmb, skolskaGodina);
        if (prijava == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji prijava za datu kombinaciju JMB i skolske godine.", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PregledJednePrijaveDialog novi = new PregledJednePrijaveDialog(this, true, skolskaGodinaa, jmb);
        novi.setVisible(true);

    }//GEN-LAST:event_prikaziPrijavuButtonActionPerformed

    private void zatvaraj(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_zatvaraj
        new KonkursniRadnikForm().setVisible(true);
    }//GEN-LAST:event_zatvaraj

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new KonkursniRadnikForm().setVisible(true);

    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/UpdateIcon.png")).getImage());

    }//GEN-LAST:event_formWindowOpened

    private void idPrijaveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPrijaveFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPrijaveFieldActionPerformed

    private void azuriraj2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azuriraj2ButtonActionPerformed
        if (!skolskaGodina3Field.getText().matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Pogrešno unijeta skolska godina. Potreban format je xxxx/yyyy.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id = -1;
        try {
            id = Integer.valueOf(idPrijaveField.getText());
        } catch (Exception ex) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu id.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        PrijavaNaKonkursDTO prijava = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijava(id, skolskaGodina3Field.getText());
        if (prijava == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji takva prijava.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        new IzmijeniPrijavuDialog(this, true, id, skolskaGodina3Field.getText()).setVisible(true);
    }//GEN-LAST:event_azuriraj2ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AzurirajPrijavuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AzurirajPrijavuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AzurirajPrijavuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AzurirajPrijavuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AzurirajPrijavuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JMBField;
    private javax.swing.JTextField JMBField1;
    private javax.swing.JButton azuriraj2Button;
    private javax.swing.JToggleButton azurirajButton;
    private javax.swing.JTextField idPrijaveField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton otkaziButton;
    private javax.swing.JButton prikaziPrijavuButton;
    private javax.swing.JButton prikaziSvePrijaveButton;
    private javax.swing.JTextField skolskaGodina3Field;
    private javax.swing.JTextField skolskaGodinaField;
    private javax.swing.JTextField skolskaGodinaField1;
    // End of variables declaration//GEN-END:variables
}
