/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.glass.events.KeyEvent;
import data.dao.DAOFactory;
import data.dto.FakultetDTO;
import data.dto.MjestoPrebivalistaDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class FakultetDialog extends javax.swing.JDialog {

    /**
     * Creates new form FakultetTableDialog
     */
    private java.awt.Frame parent;

    public FakultetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prikaziButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nazivField = new javax.swing.JTextField();
        adresaField = new javax.swing.JTextField();
        brojKrevetaField = new javax.swing.JTextField();
        dodajAzurirajButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nazivField2 = new javax.swing.JTextField();
        izbrisiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upravljanje fakultetima");
        setMaximumSize(new java.awt.Dimension(400, 342));
        setMinimumSize(new java.awt.Dimension(400, 342));

        jLabel1.setText("Prikaži listu fakulteta:");

        prikaziButton.setText("Prikaži");
        prikaziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodaj/ažuriraj"));

        jLabel2.setText("Naziv:");

        jLabel3.setText("Adresa:");

        jLabel4.setText("Broj dodijeljenih kreveta:");

        nazivField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazivFieldKeyPressed(evt);
            }
        });

        adresaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adresaFieldKeyPressed(evt);
            }
        });

        brojKrevetaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brojKrevetaFieldKeyPressed(evt);
            }
        });

        dodajAzurirajButton.setText("Dodaj/Ažuriraj");
        dodajAzurirajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajAzurirajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazivField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(adresaField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dodajAzurirajButton)
                            .addComponent(brojKrevetaField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nazivField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(adresaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brojKrevetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dodajAzurirajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Izbriši"));

        jLabel5.setText("Naziv:");

        nazivField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazivField2KeyPressed(evt);
            }
        });

        izbrisiButton.setText("Izbriši");
        izbrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbrisiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izbrisiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazivField2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nazivField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(izbrisiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(prikaziButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prikaziButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dodajAzurirajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajAzurirajButtonActionPerformed
        int brojKreveta = 0;
        String naziv = "";
        String adresa = "";

        try {
            brojKreveta = Integer.parseInt(brojKrevetaField.getText());
        } catch (Exception e) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu broja kreveta.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nazivField.getText().isEmpty()) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Polje naziva fakulteta ne smije biti prazno.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            naziv = nazivField.getText();
        }

        if (adresaField.getText().isEmpty()) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Polje adresa fakulteta ne smije biti prazno.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            adresa = adresaField.getText();
        }

        FakultetDTO staro = DAOFactory.getDAOFactory().getFakultetDAO().fakultet(naziv);
        FakultetDTO novo = new FakultetDTO(naziv, adresa, brojKreveta);
        if (staro != null) {
            new PotvrdiAzuriranjeFakultetaDialog(parent, true, staro, novo).setVisible(true);
        } else {
            boolean flag = DAOFactory.getDAOFactory().getFakultetDAO().dodajFakultet(novo);

            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno dodavanje.", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Neuspješno dodavanje!", "Greška!", JOptionPane.ERROR_MESSAGE);;
                return;
            }
        }
    }//GEN-LAST:event_dodajAzurirajButtonActionPerformed

    private void prikaziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziButtonActionPerformed
        new ListaFakultetaDialog(parent, true).setVisible(true);
    }//GEN-LAST:event_prikaziButtonActionPerformed

    private void izbrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbrisiButtonActionPerformed
        boolean flag = DAOFactory.getDAOFactory().getFakultetDAO().obrisiFakultet(nazivField2.getText());
        if (flag) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno brisanje.", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji takav podatak u bazi.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_izbrisiButtonActionPerformed

    private void nazivFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazivFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dodajAzurirajButton.doClick();
        }
    }//GEN-LAST:event_nazivFieldKeyPressed

    private void adresaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresaFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dodajAzurirajButton.doClick();
        }
    }//GEN-LAST:event_adresaFieldKeyPressed

    private void brojKrevetaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brojKrevetaFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dodajAzurirajButton.doClick();
        }
    }//GEN-LAST:event_brojKrevetaFieldKeyPressed

    private void nazivField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazivField2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            izbrisiButton.doClick();
        }
    }//GEN-LAST:event_nazivField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FakultetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FakultetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FakultetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FakultetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FakultetDialog dialog = new FakultetDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresaField;
    private javax.swing.JTextField brojKrevetaField;
    private javax.swing.JButton dodajAzurirajButton;
    private javax.swing.JButton izbrisiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nazivField;
    private javax.swing.JTextField nazivField2;
    private javax.swing.JButton prikaziButton;
    // End of variables declaration//GEN-END:variables
}
