/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dao.DAOFactory;
import data.dto.AdminDTO;
import data.dto.BlagajnikDTO;
import data.dto.KonkursniRadnikDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class IzmijeniNalogDialog extends javax.swing.JDialog {

    private BlagajnikDTO blagajnik;
    private AdminDTO admin;
    private KonkursniRadnikDTO radnik;

    public IzmijeniNalogDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public IzmijeniNalogDialog(java.awt.Frame parent, boolean modal, KonkursniRadnikDTO radnik) {
        super(parent, modal);
        initComponents();
        this.radnik = radnik;
        this.blagajnik = null;
        this.admin = null;
        setTitle("Nalog " + radnik.getUsername());
        usernameField.setText(radnik.getUsername());
        usernameField.setEditable(false);
        imeField.setText(radnik.getIme());
        prezimeField.setText(radnik.getPrezime());
        jmbField.setText(radnik.getJMB());
    }

    public IzmijeniNalogDialog(java.awt.Frame parent, boolean modal, AdminDTO admin) {
        super(parent, modal);
        initComponents();
        this.admin = admin;
        this.radnik = null;
        this.blagajnik = null;
        setTitle("Nalog " + admin.getUsername());
        usernameField.setText(admin.getUsername());
        imeField.setText(admin.getIme());
        prezimeField.setText(admin.getPrezime());
        jmbField.setText(admin.getJMB());
    }

    public IzmijeniNalogDialog(java.awt.Frame parent, boolean modal, BlagajnikDTO blagajnik) {
        super(parent, modal);
        initComponents();
        this.blagajnik = blagajnik;
        this.admin = null;
        this.radnik = null;
        setTitle("Nalog " + blagajnik.getUsername());
        usernameField.setText(blagajnik.getUsername());
        imeField.setText(blagajnik.getIme());
        prezimeField.setText(blagajnik.getPrezime());
        jmbField.setText(blagajnik.getJMB());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        imeField = new javax.swing.JTextField();
        prezimeField = new javax.swing.JTextField();
        jmbField = new javax.swing.JTextField();
        sacuvajButton = new javax.swing.JButton();
        odustaniButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Korisničko ime:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("JMB:");

        sacuvajButton.setText("Sačuvaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        odustaniButton.setText("Odustani");
        odustaniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odustaniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmbField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(prezimeField)
                    .addComponent(imeField)
                    .addComponent(usernameField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(odustaniButton)
                .addGap(28, 28, 28)
                .addComponent(sacuvajButton)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(imeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prezimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jmbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacuvajButton)
                    .addComponent(odustaniButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void odustaniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odustaniButtonActionPerformed
        new ListaNalogaDialog(new java.awt.Frame(), true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_odustaniButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new ListaNalogaDialog(new java.awt.Frame(), true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
        String username = usernameField.getText();
        String ime = imeField.getText();
        String prezime = prezimeField.getText();
        String jmb = jmbField.getText();
        if (jmb.length() != 13) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Nevalidan format JMB polja.", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (admin != null) {
            String stariUsername = admin.getUsername();
            admin.setUsername(username);
            admin.setIme(ime);
            admin.setPrezime(prezime);
            admin.setJMB(jmb);
            boolean flag = DAOFactory.getDAOFactory().getAdminDAO().azurirajAdmina(admin, stariUsername);
            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno izmijenjeni podaci o nalogu.", "", JOptionPane.INFORMATION_MESSAGE);
                new ListaNalogaDialog(new java.awt.Frame(), true).setVisible(true);
                this.dispose();
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Nije moguće izvršiti izmijene.", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if (blagajnik != null) {
            String stariUsername = blagajnik.getUsername();
            blagajnik.setUsername(username);
            blagajnik.setIme(ime);
            blagajnik.setPrezime(prezime);
            blagajnik.setJMB(jmb);
            boolean flag = DAOFactory.getDAOFactory().getBlagajnikDAO().azurirajBlagajnika(blagajnik, stariUsername);
            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno izmijenjeni podaci o nalogu.", "", JOptionPane.INFORMATION_MESSAGE);
                new ListaNalogaDialog(new java.awt.Frame(), true).setVisible(true);
                this.dispose();
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Nije moguće izvršiti izmijene.", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if (radnik != null) {
            String stariUsername = radnik.getUsername();
            radnik.setUsername(username);
            radnik.setIme(ime);
            radnik.setPrezime(prezime);
            radnik.setJMB(jmb);
            boolean flag = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().azurirajKonkursnogRadnika(radnik, stariUsername);
            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno izmijenjeni podaci o nalogu.", "", JOptionPane.INFORMATION_MESSAGE);
                new ListaNalogaDialog(new java.awt.Frame(), true).setVisible(true);
                this.dispose();
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Nije moguće izvršiti izmijene.", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmijeniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmijeniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmijeniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmijeniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmijeniNalogDialog dialog = new IzmijeniNalogDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField imeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jmbField;
    private javax.swing.JButton odustaniButton;
    private javax.swing.JTextField prezimeField;
    private javax.swing.JButton sacuvajButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
