/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dao.DAOFactory;
import data.dto.FakultetDTO;
import data.dto.PrijavaNaKonkursDTO;
import data.dto.RezultatiDTO;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class KonkursniRadnikForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    public KonkursniRadnikForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        skolskaGodinaField2 = new javax.swing.JTextField();
        generisiRezultateButton = new javax.swing.JButton();
        upravljajFakultetimaButton = new javax.swing.JButton();
        upravljajMjestimaPrebivalistaButton = new javax.swing.JButton();
        izbrisiPrijavuButton = new javax.swing.JButton();
        novaPrijavaButton = new javax.swing.JToggleButton();
        pregledPrijavaButton = new javax.swing.JToggleButton();
        azurirajPrijavuButton = new javax.swing.JToggleButton();
        odjaviSeButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pogledajRezultateButton = new javax.swing.JToggleButton();
        procitajTekstKonkursaButton = new javax.swing.JToggleButton();
        skolskaGodinaField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Studentski Dom - Rad sa konkursom");
        setMaximumSize(new java.awt.Dimension(490, 412));
        setMinimumSize(new java.awt.Dimension(490, 412));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(490, 412));
        jPanel2.setMinimumSize(new java.awt.Dimension(490, 412));
        jPanel2.setPreferredSize(new java.awt.Dimension(490, 412));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Školska godina:");

        generisiRezultateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generisiRezultateButton.setForeground(new java.awt.Color(0, 0, 255));
        generisiRezultateButton.setText("Generiši rezultate");
        generisiRezultateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generisiRezultateButtonActionPerformed(evt);
            }
        });

        upravljajFakultetimaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        upravljajFakultetimaButton.setForeground(new java.awt.Color(0, 0, 255));
        upravljajFakultetimaButton.setText("Baza fakulteta");
        upravljajFakultetimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravljajFakultetimaButtonActionPerformed(evt);
            }
        });

        upravljajMjestimaPrebivalistaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        upravljajMjestimaPrebivalistaButton.setForeground(new java.awt.Color(0, 0, 255));
        upravljajMjestimaPrebivalistaButton.setText("Baza mjesta prebivališta");
        upravljajMjestimaPrebivalistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravljajMjestimaPrebivalistaButtonActionPerformed(evt);
            }
        });

        izbrisiPrijavuButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        izbrisiPrijavuButton.setForeground(new java.awt.Color(255, 51, 51));
        izbrisiPrijavuButton.setText("Izbriši prijavu");
        izbrisiPrijavuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbrisiPrijavuButtonActionPerformed(evt);
            }
        });

        novaPrijavaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        novaPrijavaButton.setForeground(new java.awt.Color(0, 204, 0));
        novaPrijavaButton.setText("Nova prijava");
        novaPrijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaPrijavaButtonActionPerformed(evt);
            }
        });

        pregledPrijavaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pregledPrijavaButton.setForeground(new java.awt.Color(0, 0, 255));
        pregledPrijavaButton.setText("Pregled prijava");
        pregledPrijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledPrijavaButtonActionPerformed(evt);
            }
        });

        azurirajPrijavuButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        azurirajPrijavuButton.setForeground(new java.awt.Color(0, 0, 255));
        azurirajPrijavuButton.setText("Ažuriraj prijavu");
        azurirajPrijavuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azurirajPrijavuButtonActionPerformed(evt);
            }
        });

        odjaviSeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        odjaviSeButton.setForeground(new java.awt.Color(255, 0, 0));
        odjaviSeButton.setText("Odjavi se");
        odjaviSeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odjaviSeButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Školska godina:");

        pogledajRezultateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pogledajRezultateButton.setForeground(new java.awt.Color(0, 0, 255));
        pogledajRezultateButton.setText("Pogledaj rezultate");
        pogledajRezultateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogledajRezultateButtonActionPerformed(evt);
            }
        });

        procitajTekstKonkursaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        procitajTekstKonkursaButton.setForeground(new java.awt.Color(0, 0, 255));
        procitajTekstKonkursaButton.setText("Pročitaj tekst konkursa");
        procitajTekstKonkursaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procitajTekstKonkursaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(skolskaGodinaField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(procitajTekstKonkursaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pogledajRezultateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pogledajRezultateButton, procitajTekstKonkursaButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(skolskaGodinaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(procitajTekstKonkursaButton)
                .addGap(18, 18, 18)
                .addComponent(pogledajRezultateButton)
                .addGap(28, 28, 28))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 204));
        jButton1.setText("Promjeni šifru naloga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(azurirajPrijavuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(novaPrijavaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregledPrijavaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(izbrisiPrijavuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upravljajFakultetimaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upravljajMjestimaPrebivalistaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(odjaviSeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(skolskaGodinaField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generisiRezultateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(75, 75, 75))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {azurirajPrijavuButton, izbrisiPrijavuButton, novaPrijavaButton, pregledPrijavaButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaPrijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregledPrijavaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(azurirajPrijavuButton)
                    .addComponent(izbrisiPrijavuButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(upravljajFakultetimaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(upravljajMjestimaPrebivalistaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(skolskaGodinaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generisiRezultateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(odjaviSeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {azurirajPrijavuButton, izbrisiPrijavuButton, novaPrijavaButton, pregledPrijavaButton});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {upravljajFakultetimaButton, upravljajMjestimaPrebivalistaButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novaPrijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaPrijavaButtonActionPerformed
        new NovaPrijavaForm().setVisible(true);

        this.dispose();//to close the current jframe
    }//GEN-LAST:event_novaPrijavaButtonActionPerformed

    private void odjaviSeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odjaviSeButtonActionPerformed
        new LoginForm().setVisible(true);

        this.dispose();//to close the current jframe
    }//GEN-LAST:event_odjaviSeButtonActionPerformed

    private void pregledPrijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledPrijavaButtonActionPerformed
        new PregledPrijaveForm().setVisible(true);


    }//GEN-LAST:event_pregledPrijavaButtonActionPerformed

    private void azurirajPrijavuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azurirajPrijavuButtonActionPerformed
        new AzurirajPrijavuForm().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_azurirajPrijavuButtonActionPerformed

    private void izbrisiPrijavuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbrisiPrijavuButtonActionPerformed
        new IzbrisiPrijavuForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_izbrisiPrijavuButtonActionPerformed

    public static void pozoviOptionPane(Component comp, Object message, String title, int messageType) {
        JOptionPane novi = new JOptionPane();
        novi.showMessageDialog(comp, message, title, messageType);
    }

    private void procitajTekstKonkursaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procitajTekstKonkursaButtonActionPerformed
        String skolskaGodina = skolskaGodinaField.getText();

        if (!skolskaGodina.matches("\\d{4}/\\d{4}")) {
            pozoviOptionPane(this, "Greška u formatu školske godine. Potreban format xxxx/yyyy.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String putanja = DAOFactory.getDAOFactory().getKonkursDAO().readPDF(skolskaGodina);

        if (putanja.equals("")) {
            pozoviOptionPane(this, "Ne postoji tekst konkursa za tu godinu.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File(putanja);
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
                pozoviOptionPane(this, "Ne postoji aplikacija za otvaranje ovog tipa dokumenta.", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_procitajTekstKonkursaButtonActionPerformed

    private void pogledajRezultateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogledajRezultateButtonActionPerformed
        new TabelaRezultataDialog(this, true, skolskaGodinaField.getText()).setVisible(true);
    }//GEN-LAST:event_pogledajRezultateButtonActionPerformed

    private void upravljajFakultetimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravljajFakultetimaButtonActionPerformed
        new FakultetDialog(this, true).setVisible(true);
    }//GEN-LAST:event_upravljajFakultetimaButtonActionPerformed

    private void upravljajMjestimaPrebivalistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravljajMjestimaPrebivalistaButtonActionPerformed
        new MjestaPrebivalistaDialog(this, true).setVisible(true);
    }//GEN-LAST:event_upravljajMjestimaPrebivalistaButtonActionPerformed

    private void generisiRezultateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generisiRezultateButtonActionPerformed

        if (!skolskaGodinaField2.getText().matches("\\d{4}/\\d{4}")) {
            pozoviOptionPane(this, "Greška u formatu školske godine. Potreban format xxxx/yyyy.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<FakultetDTO> fakulteti = DAOFactory.getDAOFactory().getFakultetDAO().fakulteti();
        List<PrijavaNaKonkursDTO> prijave = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijave(skolskaGodinaField2.getText());
        List<RezultatiDTO> rezultati = DAOFactory.getDAOFactory().getRezultatiDAO().rezultati(skolskaGodinaField2.getText());

        for (PrijavaNaKonkursDTO prijava : prijave) {
            DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().bodujPrijavu(skolskaGodinaField2.getText(), prijava.getJMB());
        }

        int brojKreveta = 0;

        for (FakultetDTO faks : fakulteti) {
            brojKreveta = faks.getBrojDodjeljenihKreveta();
            for (PrijavaNaKonkursDTO pri : prijave) {
                if (pri.getNazivFakulteta().equals(faks.getNazivFakulteta())) {
                    for (RezultatiDTO rez : rezultati) {
                        if (pri.getIdPrijave() == rez.getIdPrijave()) {

                            if (brojKreveta > 0) {
                                rez.setProsaoNaKonkursu(true);
                                brojKreveta--;
                                DAOFactory.getDAOFactory().getRezultatiDAO().azurirajRezultat(rez);
                            } else {
                                rez.setProsaoNaKonkursu(false);
                                DAOFactory.getDAOFactory().getRezultatiDAO().azurirajRezultat(rez);
                            }

                        }
                    }
                }
            }
        }

        pozoviOptionPane(this, "Rezultati su generisani.", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_generisiRezultateButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/OpenIcon.png")).getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new PromjeniSifruDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonkursniRadnikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonkursniRadnikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonkursniRadnikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonkursniRadnikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonkursniRadnikForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton azurirajPrijavuButton;
    private javax.swing.JButton generisiRezultateButton;
    private javax.swing.JButton izbrisiPrijavuButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton novaPrijavaButton;
    private javax.swing.JToggleButton odjaviSeButton;
    private javax.swing.JToggleButton pogledajRezultateButton;
    private javax.swing.JToggleButton pregledPrijavaButton;
    private javax.swing.JToggleButton procitajTekstKonkursaButton;
    private javax.swing.JTextField skolskaGodinaField;
    private javax.swing.JTextField skolskaGodinaField2;
    private javax.swing.JButton upravljajFakultetimaButton;
    private javax.swing.JButton upravljajMjestimaPrebivalistaButton;
    // End of variables declaration//GEN-END:variables
}
