/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dao.DAOFactory;
import data.dto.AdminDTO;
import data.dto.BlagajnikDTO;
import data.dto.KonkursniRadnikDTO;
import java.security.SecureRandom;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class KreiranjeNovogNalogaDialog extends javax.swing.JDialog {

    /**
     * Creates new form NoviNalogDialog
     */
    public KreiranjeNovogNalogaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminButton = new javax.swing.JRadioButton();
        konkursniButton = new javax.swing.JRadioButton();
        blagajnikButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        imeField = new javax.swing.JTextField();
        prezimeField = new javax.swing.JTextField();
        JMBField = new javax.swing.JTextField();
        kreirajButton = new javax.swing.JButton();
        odustaniButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        repeatPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiranje novog naloga");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        adminButton.setText("Administrator");

        konkursniButton.setText("Konkursni radnik");

        blagajnikButton.setText("Blagajnik");

        jLabel1.setText("Vrsta naloga:");

        jLabel2.setText("Korisničko ime:");

        jLabel3.setText("Lozinka:");

        jLabel4.setText("Ponovite lozinku:");

        jLabel5.setText("Podaci o korisniku naloga[neobavezni podaci]:");

        jLabel6.setText("Ime:");

        jLabel7.setText("Prezime:");

        jLabel8.setText("JMB:");

        imeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeFieldActionPerformed(evt);
            }
        });

        kreirajButton.setText("Kreiraj nalog");
        kreirajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajButtonActionPerformed(evt);
            }
        });

        odustaniButton.setText("Odustani");
        odustaniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odustaniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(konkursniButton)
                            .addComponent(blagajnikButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imeField)
                                    .addComponent(prezimeField)
                                    .addComponent(JMBField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(adminButton))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(odustaniButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kreirajButton)
                .addGap(123, 123, 123))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminButton, blagajnikButton, konkursniButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminButton))
                        .addGap(3, 3, 3)
                        .addComponent(konkursniButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(blagajnikButton)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(imeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(prezimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JMBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kreirajButton)
                    .addComponent(odustaniButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminButton, blagajnikButton, konkursniButton});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeFieldActionPerformed

    private void odustaniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odustaniButtonActionPerformed
        new AdminForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_odustaniButtonActionPerformed

    private void kreirajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajButtonActionPerformed
        if (usernameField.getText().equals("") || passwordField.getText().equals("") || repeatPasswordField.getText().equals("")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Morate popuni polja koja se tiču korisničkog imena i lozinke.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!passwordField.getText().equals(repeatPasswordField.getText())) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Lozinka i ponovljena lozinka nisu iste.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (passwordField.getText().length() < 8) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Lozinka mora biti duža od 8 karaktera.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        KonkursniRadnikDTO kr = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().konkursniRadnik(usernameField.getText());
        AdminDTO a = DAOFactory.getDAOFactory().getAdminDAO().admin(usernameField.getText());
        BlagajnikDTO b = DAOFactory.getDAOFactory().getBlagajnikDAO().blagajnik(usernameField.getText());

        if (kr != null || a != null || b != null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Korisničko ime je zauzeto!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = usernameField.getText();
        String lozinka = passwordField.getText();
        String ime = imeField.getText();
        String prezime = prezimeField.getText();
        String jmb = JMBField.getText();
        String salt = randomString(9);
        String hesiranaLozinka = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().get_SHA_512_SecurePassword(lozinka, salt);
        Calendar calendar = Calendar.getInstance();
        java.sql.Date datum = new java.sql.Date(calendar.getTime().getTime());

        if (konkursniButton.isSelected()) {
            KonkursniRadnikDTO radnik = new KonkursniRadnikDTO(username, hesiranaLozinka, salt, ime, prezime, jmb, datum, true);
            boolean flag = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().dodajKonkursnogRadnika(radnik);
            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno kreiran nalog.", "Greška!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Nalog nije kreiran!", "Greška!", JOptionPane.ERROR_MESSAGE);
            }

        } else if (adminButton.isSelected()) {
            AdminDTO radnik = new AdminDTO(username, hesiranaLozinka, salt, ime, prezime, jmb, datum, true);
            boolean flag = DAOFactory.getDAOFactory().getAdminDAO().dodajAdmina(radnik);
            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno kreiran nalog.", "Greška!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Nalog nije kreiran!", "Greška!", JOptionPane.ERROR_MESSAGE);
            }
        } else if (blagajnikButton.isSelected()) {
            BlagajnikDTO radnik = new BlagajnikDTO(username, hesiranaLozinka, salt, ime, prezime, jmb, datum, true);
            boolean flag = DAOFactory.getDAOFactory().getBlagajnikDAO().dodajBlagajnika(radnik);
            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno kreiran nalog.", "Greška!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Nalog nije kreiran!", "Greška!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            KonkursniRadnikForm.pozoviOptionPane(this, "Morate odabrati vrstu naloga.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.dispose();
        new AdminForm().setVisible(true);
    }//GEN-LAST:event_kreirajButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new AdminForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    static final String AB = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    static SecureRandom rnd = new SecureRandom();

    static String randomString(int len) {
        StringBuilder sb = new StringBuilder(len);
        for (int i = 0; i < len; i++) {
            sb.append(AB.charAt(rnd.nextInt(AB.length())));
        }
        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreiranjeNovogNalogaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreiranjeNovogNalogaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreiranjeNovogNalogaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreiranjeNovogNalogaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KreiranjeNovogNalogaDialog dialog = new KreiranjeNovogNalogaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JMBField;
    private javax.swing.JRadioButton adminButton;
    private javax.swing.JRadioButton blagajnikButton;
    private javax.swing.JTextField imeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton konkursniButton;
    private javax.swing.JButton kreirajButton;
    private javax.swing.JButton odustaniButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField prezimeField;
    private javax.swing.JPasswordField repeatPasswordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
