/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.glass.events.KeyEvent;
import data.dao.DAOFactory;
import data.dto.*;
import java.awt.event.ActionEvent;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class LoginForm extends javax.swing.JFrame {

    public static String username;
    public static String vrsta;
    private ButtonGroup grupa;

    public LoginForm() {
        initComponents();
        this.grupa = new ButtonGroup();
        grupa.add(adminButton);
        grupa.add(konkursniButton);
        grupa.add(blagajnikButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prijavaButton = new javax.swing.JToggleButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        adminButton = new javax.swing.JRadioButton();
        konkursniButton = new javax.swing.JRadioButton();
        blagajnikButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Studentski Dom");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 204, 255));
        setMaximumSize(new java.awt.Dimension(360, 220));
        setMinimumSize(new java.awt.Dimension(360, 220));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        prijavaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prijavaButton.setForeground(new java.awt.Color(0, 51, 255));
        prijavaButton.setText("Prijava");
        prijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaButtonActionPerformed(evt);
            }
        });

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");

        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("Administrator");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        konkursniButton.setForeground(new java.awt.Color(255, 255, 255));
        konkursniButton.setText("Konkursni radnik");

        blagajnikButton.setForeground(new java.awt.Color(255, 255, 255));
        blagajnikButton.setText("Blagajnik");
        blagajnikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blagajnikButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(konkursniButton)
                        .addGap(28, 28, 28)
                        .addComponent(blagajnikButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blagajnikButton)
                    .addComponent(adminButton)
                    .addComponent(konkursniButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(prijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordField, usernameField});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void prijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavaButtonActionPerformed

        if (konkursniButton.isSelected()) {

            String username = usernameField.getText();
            char[] pass = passwordField.getPassword();
            String password = String.valueOf(pass);

            LoginForm.username = username;
            LoginForm.vrsta = "Konkursni radnik";

            KonkursniRadnikDTO radnik = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().konkursniRadnik(username);
            if (radnik == null) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Greska pri unosu podataka.", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                String hesiraniPassword = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().get_SHA_512_SecurePassword(password, radnik.getSalt());
                if (hesiraniPassword.equals(radnik.getPasswordHash())) {
                    KonkursniRadnikForm.pozoviOptionPane(this, "Uspjesna prijava!", "", JOptionPane.INFORMATION_MESSAGE);

                    //new KonkursniRadnikForm().setVisible(true);
                    new KonkursniRadnikOpcijeForm().setVisible(true);

                    this.dispose();

                    return;
                } else {
                    KonkursniRadnikForm.pozoviOptionPane(this, "Greska pri unosu podataka.", "Greska!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } else if (adminButton.isSelected()) {

            String username = usernameField.getText();
            char[] pass = passwordField.getPassword();
            String password = String.valueOf(pass);

            LoginForm.username = username;
            LoginForm.vrsta = "Admin";

            AdminDTO admin = DAOFactory.getDAOFactory().getAdminDAO().admin(username);
            if (admin == null) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu podataka.", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                String hesiraniPassword = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().get_SHA_512_SecurePassword(password, admin.getSalt());
                if (hesiraniPassword.equals(admin.getPasswordHash())) {
                    KonkursniRadnikForm.pozoviOptionPane(this, "Uspješna prijava!", "", JOptionPane.INFORMATION_MESSAGE);

                    new AdminForm().setVisible(true);

                    this.dispose();
                } else {
                    KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu podataka.", "Greška!", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else if (blagajnikButton.isSelected()) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Trenutno nedostupno. ", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            KonkursniRadnikForm.pozoviOptionPane(this, "Morate odabrati vrstu naloga.", "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_prijavaButtonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            prijavaButton.doClick();
        }
    }//GEN-LAST:event_formKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            prijavaButton.doClick();
        }

    }//GEN-LAST:event_passwordFieldKeyPressed

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            prijavaButton.doClick();
        }

    }//GEN-LAST:event_usernameFieldKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/OpenIcon.png")).getImage());
    }//GEN-LAST:event_formWindowOpened

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonActionPerformed

    private void blagajnikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blagajnikButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blagajnikButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminButton;
    private javax.swing.JRadioButton blagajnikButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton konkursniButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JToggleButton prijavaButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
