/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.glass.events.KeyEvent;
import data.dao.DAOFactory;
import data.dto.MjestoPrebivalistaDTO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class MjestaPrebivalistaDialog extends javax.swing.JDialog {

    /**
     * Creates new form MjestaPrebivalistaTableDialog
     */
    private java.awt.Frame parent;

    public MjestaPrebivalistaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prikaziTrenutnoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        udaljenostField = new javax.swing.JTextField();
        nazivField = new javax.swing.JTextField();
        brojPosteField = new javax.swing.JTextField();
        dodajAzurirajButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlabelneki = new javax.swing.JLabel();
        brojPosteField2 = new javax.swing.JTextField();
        izbrisiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upravljanje mjestima prebivališta");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        prikaziTrenutnoButton.setText("Prikaži");
        prikaziTrenutnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziTrenutnoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Prikaži trenutno stanje:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodaj/Ažuriraj"));

        jLabel2.setText("Naziv:");

        jLabel3.setText("Broj pošte:");

        jLabel4.setText("Udaljenost(KM):");

        udaljenostField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                udaljenostFieldKeyPressed(evt);
            }
        });

        nazivField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazivFieldKeyPressed(evt);
            }
        });

        brojPosteField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brojPosteFieldKeyPressed(evt);
            }
        });

        dodajAzurirajButton.setText("Dodaj");
        dodajAzurirajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajAzurirajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dodajAzurirajButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazivField)
                            .addComponent(udaljenostField)
                            .addComponent(brojPosteField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(brojPosteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(udaljenostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(nazivField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(dodajAzurirajButton))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Izbriši postojeće"));

        jlabelneki.setText("Broj pošte:");

        brojPosteField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brojPosteField2ActionPerformed(evt);
            }
        });
        brojPosteField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brojPosteField2KeyPressed(evt);
            }
        });

        izbrisiButton.setText("Izbriši");
        izbrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbrisiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(izbrisiButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlabelneki)
                        .addGap(18, 18, 18)
                        .addComponent(brojPosteField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelneki)
                    .addComponent(brojPosteField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(izbrisiButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prikaziTrenutnoButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prikaziTrenutnoButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prikaziTrenutnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziTrenutnoButtonActionPerformed
        new TabelaDialog(parent, true).setVisible(true);
    }//GEN-LAST:event_prikaziTrenutnoButtonActionPerformed

    private void brojPosteField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brojPosteField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brojPosteField2ActionPerformed

    private void dodajAzurirajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajAzurirajButtonActionPerformed
        int brojPoste = 0;
        String naziv = "";
        double udaljenost = 0;

        try {
            brojPoste = Integer.parseInt(brojPosteField.getText());
        } catch (Exception e) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu broja pošte.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nazivField.getText().isEmpty()) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu naziva mjesta.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            naziv = nazivField.getText();
        }

        try {
            udaljenost = Double.parseDouble(udaljenostField.getText());
        } catch (Exception e) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu udaljenosti.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        MjestoPrebivalistaDTO staro = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().mjestoPrebivalista(brojPoste);
        MjestoPrebivalistaDTO mjesto = new MjestoPrebivalistaDTO(brojPoste, naziv, udaljenost);
        boolean postojiLi = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().postojiLiIstoOvakvo(brojPoste, naziv, udaljenost);
        if (staro != null) {
            new PotvrdiAzuriranjeMjestaDialog(parent, true, staro, mjesto).setVisible(true);
        } else {
            boolean flag = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().dodajMjestoPrebivalista(mjesto);

            if (flag) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno dodavanje!", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Neuspješno dodavanje!", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

    }//GEN-LAST:event_dodajAzurirajButtonActionPerformed

    private void izbrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbrisiButtonActionPerformed
        int brojPoste = 0;
        try {
            brojPoste = Integer.parseInt(brojPosteField2.getText());
            MjestoPrebivalistaDTO mjesto = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().mjestoPrebivalista(brojPoste);
            if (mjesto == null) {
                throw new Exception();
            }
            boolean obrisano = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().obrisiMjestoPrebivalista(brojPoste);
            if (obrisano == true) {
                KonkursniRadnikForm.pozoviOptionPane(this, "Obrisano!", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                KonkursniRadnikForm.pozoviOptionPane(this, "Brisanje nije dozvoljeno!", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji takav podatak u bazi!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_izbrisiButtonActionPerformed

    private void udaljenostFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_udaljenostFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dodajAzurirajButton.doClick();
        }
    }//GEN-LAST:event_udaljenostFieldKeyPressed

    private void nazivFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazivFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dodajAzurirajButton.doClick();
        }
    }//GEN-LAST:event_nazivFieldKeyPressed

    private void brojPosteFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brojPosteFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dodajAzurirajButton.doClick();
        }
    }//GEN-LAST:event_brojPosteFieldKeyPressed

    private void brojPosteField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brojPosteField2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            izbrisiButton.doClick();
        }
    }//GEN-LAST:event_brojPosteField2KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/OpenIcon.png")).getImage());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MjestaPrebivalistaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MjestaPrebivalistaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MjestaPrebivalistaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MjestaPrebivalistaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MjestaPrebivalistaDialog dialog = new MjestaPrebivalistaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brojPosteField;
    private javax.swing.JTextField brojPosteField2;
    private javax.swing.JButton dodajAzurirajButton;
    private javax.swing.JButton izbrisiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlabelneki;
    private javax.swing.JTextField nazivField;
    private javax.swing.JButton prikaziTrenutnoButton;
    private javax.swing.JTextField udaljenostField;
    // End of variables declaration//GEN-END:variables
}
