/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dao.DAOFactory;
import data.dto.FakultetDTO;
import data.dto.MjestoPrebivalistaDTO;
import data.dto.PrijavaNaKonkursDTO;
import data.dto.StudentDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DulleX
 */
public class PregledPrijavaSkolskeGodineDialog extends javax.swing.JDialog {

    static String skolskaGodina;

    public PregledPrijavaSkolskeGodineDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PregledPrijavaSkolskeGodineDialog(java.awt.Frame parent, boolean modal, String skolskaGodina, String fakultet) {
        super(parent, modal);
        initComponents();
        PregledPrijavaSkolskeGodineDialog.skolskaGodina = skolskaGodina;
        skolskaGodinaField.setText(skolskaGodina);

        List<PrijavaNaKonkursDTO> lista = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijave(skolskaGodina);
        DefaultTableModel model;
        StudentDTO student = new StudentDTO();
        MjestoPrebivalistaDTO mjesto = new MjestoPrebivalistaDTO();
        FakultetDTO faks;

        for (PrijavaNaKonkursDTO prijava : lista) {

            student = DAOFactory.getDAOFactory().getStudentDAO().student(prijava.getJMB());
            mjesto = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().mjestoPrebivalista(prijava.getBrojPoste());
            faks = DAOFactory.getDAOFactory().getFakultetDAO().fakultet(prijava.getNazivFakulteta());

            if (faks.getNazivFakulteta().equals(fakultet)) {
                Object[] row = {prijava.getIdPrijave(), prijava.getJMB(), student.getIme(), student.getPrezime(), mjesto.getNaziv(), prijava.getNazivFakulteta(), prijava.getSkolskaGodina(), prijava.getProsjekOcjena(), prijava.getBrojObnovljenihGodina(), prijava.getTelefon(), prijava.getEmail()};

                model = (DefaultTableModel) tabelica.getModel();

                model.addRow(row);
            }
        }

        setTitle("Pregled prijava za " + fakultet + " fakultet");
    }

    public PregledPrijavaSkolskeGodineDialog(java.awt.Frame parent, boolean modal, String skolskaGodina) {
        super(parent, modal);
        initComponents();
        PregledPrijavaSkolskeGodineDialog.skolskaGodina = skolskaGodina;
        skolskaGodinaField.setText(skolskaGodina);

        List<PrijavaNaKonkursDTO> lista = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijave(skolskaGodina);
        DefaultTableModel model;
        StudentDTO student = new StudentDTO();
        MjestoPrebivalistaDTO mjesto = new MjestoPrebivalistaDTO();

        for (PrijavaNaKonkursDTO prijava : lista) {

            student = DAOFactory.getDAOFactory().getStudentDAO().student(prijava.getJMB());
            mjesto = DAOFactory.getDAOFactory().getMjestoPrebivalistaDAO().mjestoPrebivalista(prijava.getBrojPoste());

            Object[] row = {prijava.getIdPrijave(), prijava.getJMB(), student.getIme(), student.getPrezime(), mjesto.getNaziv(), prijava.getNazivFakulteta(), prijava.getSkolskaGodina(), prijava.getProsjekOcjena(), prijava.getBrojObnovljenihGodina(), prijava.getTelefon(), prijava.getEmail()};

            model = (DefaultTableModel) tabelica.getModel();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelica = new javax.swing.JTable();
        skolskaGodinaField = new javax.swing.JTextField();
        socijalniStatusButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        socijalniStatusField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled prijava");
        setResizable(false);

        jLabel1.setText("Školska godina:");

        tabelica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id prijave", "JMB", "Ime", "Prezime", "Mjesto prebivališta", "Fakultet", "Godina studija", "Prosjek ocjena", "Broj obnovljenih godina", "Telefon", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelica);

        socijalniStatusButton.setText("Pogledaj");
        socijalniStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socijalniStatusButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Socijalni status za id: ");

        socijalniStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socijalniStatusFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(skolskaGodinaField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(socijalniStatusField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(socijalniStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(416, 416, 416))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(skolskaGodinaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socijalniStatusButton)
                    .addComponent(jLabel2)
                    .addComponent(socijalniStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void socijalniStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socijalniStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socijalniStatusFieldActionPerformed

    private void socijalniStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socijalniStatusButtonActionPerformed
        String id = socijalniStatusField.getText();
        int flag = 0;

        DefaultTableModel model = (DefaultTableModel) tabelica.getModel();

        for (int i = 0; i < tabelica.getRowCount(); i++) {
            String value = tabelica.getModel().getValueAt(i, 0).toString();
            if (id.equals(value)) {
                flag = 1;
            }
        }
        if (flag == 1) {
            SocijalniDiagram novi = new SocijalniDiagram(new KonkursniRadnikForm(), true, Integer.valueOf(id), skolskaGodinaField.getText());
            novi.setVisible(true);
        } else {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji traženi id.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_socijalniStatusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavaSkolskeGodineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavaSkolskeGodineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavaSkolskeGodineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavaSkolskeGodineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PregledPrijavaSkolskeGodineDialog dialog = new PregledPrijavaSkolskeGodineDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField skolskaGodinaField;
    private javax.swing.JToggleButton socijalniStatusButton;
    private javax.swing.JTextField socijalniStatusField;
    private javax.swing.JTable tabelica;
    // End of variables declaration//GEN-END:variables
}
