/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.glass.events.KeyEvent;
import data.dao.DAOFactory;
import static data.dao.DAOFactory.getDAOFactory;
import data.dto.FakultetDTO;
import data.dto.PrijavaNaKonkursDTO;
import data.dto.StudentDTO;
import static forms.PregledPrijavaSkolskeGodineDialog.skolskaGodina;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class PregledPrijaveForm extends javax.swing.JFrame {

    /**
     * Creates new form PregledPrijaveForm
     */
    public PregledPrijaveForm() {
        initComponents();

        List<FakultetDTO> lista = DAOFactory.getDAOFactory().getFakultetDAO().fakulteti();

        for (FakultetDTO faks : lista) {
            fakultetCombo.addItem(faks.getNazivFakulteta());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JMBField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        skolskaGodinaField = new javax.swing.JTextField();
        prikaziButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        skolskaGodinaField2 = new javax.swing.JTextField();
        prikaziButton2 = new javax.swing.JToggleButton();
        otkaziButton = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        skolskaGodinaField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fakultetCombo = new javax.swing.JComboBox<>();
        prikaziButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pregled prijava");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                iksic(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pronađi prijavu studenta"));

        jLabel1.setText("JMB:");

        JMBField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JMBFieldKeyPressed(evt);
            }
        });

        jLabel2.setText("Školska godina:");

        skolskaGodinaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                skolskaGodinaFieldKeyPressed(evt);
            }
        });

        prikaziButton.setText("Prikaži");
        prikaziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prikaziButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JMBField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skolskaGodinaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JMBField, skolskaGodinaField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JMBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(skolskaGodinaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prikaziButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JMBField, skolskaGodinaField});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaži sve prijave"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Školska godina:");

        skolskaGodinaField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                skolskaGodinaField2KeyPressed(evt);
            }
        });

        prikaziButton2.setText("Prikaži");
        prikaziButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prikaziButton2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(skolskaGodinaField2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skolskaGodinaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(prikaziButton2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        otkaziButton.setText("Otkaži");
        otkaziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otkaziButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaži sve prijave studenata istog fakulteta"));

        jLabel4.setText("Školska godina:");

        skolskaGodinaField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skolskaGodinaField3ActionPerformed(evt);
            }
        });
        skolskaGodinaField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                skolskaGodinaField3KeyPressed(evt);
            }
        });

        jLabel5.setText("Fakultet:");

        fakultetCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fakultetComboKeyPressed(evt);
            }
        });

        prikaziButton3.setText("Prikaži");
        prikaziButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prikaziButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skolskaGodinaField3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fakultetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(skolskaGodinaField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fakultetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prikaziButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(otkaziButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otkaziButton)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prikaziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziButtonActionPerformed
        String skolskaGodinaa = skolskaGodinaField.getText();

        if (!skolskaGodinaa.matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu školske godine. Potreban format je xxxx/yyyy.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jmb = JMBField.getText();
        if (jmb.length() != 13) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu JMB.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StudentDTO student = DAOFactory.getDAOFactory().getStudentDAO().student(jmb);
        if (student == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška pri unosu JMB.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PrijavaNaKonkursDTO prijava = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijava(jmb, skolskaGodinaa);
        if (prijava == null) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Ne postoji prijava za datu kombinaciju JMB i školske godine.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PregledJednePrijaveDialog novi = new PregledJednePrijaveDialog(this, true, skolskaGodinaa, jmb);
        novi.setVisible(true);

    }//GEN-LAST:event_prikaziButtonActionPerformed

    private void prikaziButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziButton2ActionPerformed
        String skolskaGodinaa = skolskaGodinaField2.getText();

        if (!skolskaGodinaa.matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Pogrešno unijeta školska godina. Potreban format je xxxx/yyyy", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PregledPrijavaSkolskeGodineDialog novi = new PregledPrijavaSkolskeGodineDialog(this, true, skolskaGodinaa);
        novi.setVisible(true);
    }//GEN-LAST:event_prikaziButton2ActionPerformed

    private void skolskaGodinaField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skolskaGodinaField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skolskaGodinaField3ActionPerformed

    private void prikaziButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziButton3ActionPerformed
        String skolskaGodinaa = skolskaGodinaField3.getText();

        if (!skolskaGodinaa.matches("\\d{4}/\\d{4}")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Pogrešno unijeta školska godina. Potreban format je xxxx/yyyy.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fakultet = (String) fakultetCombo.getSelectedItem();

        PregledPrijavaSkolskeGodineDialog novi = new PregledPrijavaSkolskeGodineDialog(this, true, skolskaGodinaa, fakultet);
        novi.setVisible(true);
    }//GEN-LAST:event_prikaziButton3ActionPerformed

    private void otkaziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otkaziButtonActionPerformed
        dispose();
    }//GEN-LAST:event_otkaziButtonActionPerformed

    private void iksic(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_iksic
        dispose();
    }//GEN-LAST:event_iksic

    private void JMBFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JMBFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            prikaziButton.doClick();
        }
    }//GEN-LAST:event_JMBFieldKeyPressed

    private void skolskaGodinaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_skolskaGodinaFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            prikaziButton.doClick();
        }
    }//GEN-LAST:event_skolskaGodinaFieldKeyPressed

    private void skolskaGodinaField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_skolskaGodinaField2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            prikaziButton2.doClick();
        }
    }//GEN-LAST:event_skolskaGodinaField2KeyPressed

    private void skolskaGodinaField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_skolskaGodinaField3KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            prikaziButton3.doClick();
        }
    }//GEN-LAST:event_skolskaGodinaField3KeyPressed

    private void fakultetComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fakultetComboKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            prikaziButton3.doClick();
        }
    }//GEN-LAST:event_fakultetComboKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/LookIcon.png")).getImage());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledPrijaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledPrijaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledPrijaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledPrijaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledPrijaveForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JMBField;
    private javax.swing.JComboBox<String> fakultetCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton otkaziButton;
    private javax.swing.JButton prikaziButton;
    private javax.swing.JToggleButton prikaziButton2;
    private javax.swing.JButton prikaziButton3;
    private javax.swing.JTextField skolskaGodinaField;
    private javax.swing.JTextField skolskaGodinaField2;
    private javax.swing.JTextField skolskaGodinaField3;
    // End of variables declaration//GEN-END:variables
}
