/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dao.DAOFactory;
import data.dao.KonkursniRadnikDAO;
import data.dto.KonkursniRadnikDTO;
import java.security.SecureRandom;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author DulleX
 */
public class PromjeniSifruDialog extends javax.swing.JDialog {

    /**
     * Creates new form PromjeniSifruDialog
     */
    public PromjeniSifruDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Nalog: " + LoginForm.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sacuvajButton = new javax.swing.JButton();
        odustaniButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        trenutnaField = new javax.swing.JTextField();
        novaField = new javax.swing.JPasswordField();
        repeatField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        sacuvajButton.setText("Sačuvaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        odustaniButton.setText("Odustani");
        odustaniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odustaniButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Trenutna lozinka:");

        jLabel2.setText("Nova lozinka:");

        jLabel3.setText("Ponovite novu lozinku:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(odustaniButton)
                .addGap(18, 18, 18)
                .addComponent(sacuvajButton)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(repeatField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(trenutnaField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novaField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(trenutnaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(novaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(repeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacuvajButton)
                    .addComponent(odustaniButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void odustaniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odustaniButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_odustaniButtonActionPerformed

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
        String staraSifra = trenutnaField.getText();

        char[] pass = novaField.getPassword();
        String password = String.valueOf(pass);

        char[] pass2 = repeatField.getPassword();
        String password2 = String.valueOf(pass2);

        if (staraSifra.equals("") || password.equals("") || password2.equals("")) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Morate popuniti sva polja.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.length() < 8) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Lozinka mora biti duža od 8 karaktera.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(password2)) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Polja sa novom šifrom se ne poklapaju.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        KonkursniRadnikDTO radnik = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().konkursniRadnik(LoginForm.username);
        String hesiraniStariPassword = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().get_SHA_512_SecurePassword(staraSifra, radnik.getSalt());

        if (!hesiraniStariPassword.equals(radnik.getPasswordHash())) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Greška u unosu trenutne šifre.", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Random rand = new Random();
        int duzina = rand.nextInt(19);
        String noviSalt = randomString(duzina);
        String noviHashiraniPassword = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().get_SHA_512_SecurePassword(password, noviSalt);

        radnik.setSalt(noviSalt);
        radnik.setPasswordHash(noviHashiraniPassword);

        boolean flag = DAOFactory.getDAOFactory().getKonkursniRadnikDAO().azurirajKonkursnogRadnika2(radnik);
        if (flag) {
            KonkursniRadnikForm.pozoviOptionPane(this, "Uspješno promjenjena šifra.", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            KonkursniRadnikForm.pozoviOptionPane(this, "Nije moguće promjeniti šifru.", "Greška!", JOptionPane.ERROR_MESSAGE);
        }

        dispose();
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    static final String AB = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    static SecureRandom rnd = new SecureRandom();

    static String randomString(int len) {
        StringBuilder sb = new StringBuilder(len);
        for (int i = 0; i < len; i++) {
            sb.append(AB.charAt(rnd.nextInt(AB.length())));
        }
        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromjeniSifruDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromjeniSifruDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromjeniSifruDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromjeniSifruDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PromjeniSifruDialog dialog = new PromjeniSifruDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField novaField;
    private javax.swing.JButton odustaniButton;
    private javax.swing.JPasswordField repeatField;
    private javax.swing.JButton sacuvajButton;
    private javax.swing.JTextField trenutnaField;
    // End of variables declaration//GEN-END:variables
}
