/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dao.DAOFactory;
import data.dto.PrijavaNaKonkursDTO;
import data.dto.SocijalniStatusDTO;

/**
 *
 * @author DulleX
 */
public class SocijalniDiagram extends javax.swing.JDialog {

    public SocijalniDiagram(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public SocijalniDiagram(java.awt.Frame parent, boolean modal, int id, String skolskaGodina) {
        super(parent, modal);
        initComponents();
        IDField.setText(String.valueOf(id));
        IDField.setEditable(false);
        skolskaGodinaField.setText(skolskaGodina);
        skolskaGodinaField.setEditable(false);

        PrijavaNaKonkursDTO prijava = DAOFactory.getDAOFactory().getPrijavaNaKonkursDAO().prijava(id, skolskaGodina);

        SocijalniStatusDTO soc = DAOFactory.getDAOFactory().getSocijalniStatusDAO().socijalniStatus(prijava.getIdSocijalnogStatusa());

        bezObaRoditeljaCheck.setSelected(soc.isBezObaRoditelja());
        dijetePalogINestalogBorcaRSCheck.setSelected(soc.isDijetePalogINestalogBorcaRS());
        bezJednogRoditeljaCheck.setSelected(soc.isBezJednogRoditelja());
        invaliditetCheck.setSelected(soc.isInvaliditet());
        korisnikSocijalnePomociCheck.setSelected(soc.isKorisnikSocijalnePomoci());
        dijeteRVIVRSCheck.setSelected(soc.isDijeteRVIVRS());
        obaRoditeljaNezaposlenaCheck.setSelected(soc.isObaRoditeljaNezaposlena());
        jedanRoditeljNezaposlenCheck.setSelected(soc.isJedanRoditeljNezaposlen());
        studentiIzViseclanihPorodicaCheck.setSelected(soc.isStudentIzViseclanihPorodica());

        bezObaRoditeljaCheck.setEnabled(false);
        dijetePalogINestalogBorcaRSCheck.setEnabled(false);
        bezJednogRoditeljaCheck.setEnabled(false);
        invaliditetCheck.setEnabled(false);
        korisnikSocijalnePomociCheck.setEnabled(false);
        dijetePalogINestalogBorcaRSCheck.setEnabled(false);
        obaRoditeljaNezaposlenaCheck.setEnabled(false);
        jedanRoditeljNezaposlenCheck.setEnabled(false);
        studentiIzViseclanihPorodicaCheck.setEnabled(false);
        dijeteRVIVRSCheck.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        bezObaRoditeljaCheck = new javax.swing.JCheckBox();
        dijetePalogINestalogBorcaRSCheck = new javax.swing.JCheckBox();
        bezJednogRoditeljaCheck = new javax.swing.JCheckBox();
        invaliditetCheck = new javax.swing.JCheckBox();
        korisnikSocijalnePomociCheck = new javax.swing.JCheckBox();
        dijeteRVIVRSCheck = new javax.swing.JCheckBox();
        obaRoditeljaNezaposlenaCheck = new javax.swing.JCheckBox();
        jedanRoditeljNezaposlenCheck = new javax.swing.JCheckBox();
        studentiIzViseclanihPorodicaCheck = new javax.swing.JCheckBox();
        ee = new javax.swing.JLabel();
        skolskaGodinaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Socijalni status");
        setResizable(false);

        jLabel1.setText("Id prijave:");

        bezObaRoditeljaCheck.setText("Bez oba roditelja");

        dijetePalogINestalogBorcaRSCheck.setText("Dijete palog i nestalog borca RS");

        bezJednogRoditeljaCheck.setText("Bez jednog roditelja");

        invaliditetCheck.setText("Invaliditet");

        korisnikSocijalnePomociCheck.setText("Korisnik socijalne pomoci");

        dijeteRVIVRSCheck.setText("Dijete RVI VRS");

        obaRoditeljaNezaposlenaCheck.setText("Oba roditelja nezaposlena");

        jedanRoditeljNezaposlenCheck.setText("Jedan roditelj nezaposlen");

        studentiIzViseclanihPorodicaCheck.setText("Student iz viseclane porodice");

        ee.setText("Skolska godina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(korisnikSocijalnePomociCheck)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bezObaRoditeljaCheck)
                            .addComponent(dijetePalogINestalogBorcaRSCheck)
                            .addComponent(bezJednogRoditeljaCheck)
                            .addComponent(invaliditetCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentiIzViseclanihPorodicaCheck)
                            .addComponent(jedanRoditeljNezaposlenCheck)
                            .addComponent(dijeteRVIVRSCheck)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ee)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(skolskaGodinaField))
                                .addComponent(obaRoditeljaNezaposlenaCheck)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ee)
                    .addComponent(skolskaGodinaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bezObaRoditeljaCheck)
                    .addComponent(dijeteRVIVRSCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dijetePalogINestalogBorcaRSCheck)
                    .addComponent(obaRoditeljaNezaposlenaCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bezJednogRoditeljaCheck)
                    .addComponent(jedanRoditeljNezaposlenCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invaliditetCheck)
                    .addComponent(studentiIzViseclanihPorodicaCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(korisnikSocijalnePomociCheck)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocijalniDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocijalniDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocijalniDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocijalniDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SocijalniDiagram dialog = new SocijalniDiagram(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JCheckBox bezJednogRoditeljaCheck;
    private javax.swing.JCheckBox bezObaRoditeljaCheck;
    private javax.swing.JCheckBox dijetePalogINestalogBorcaRSCheck;
    private javax.swing.JCheckBox dijeteRVIVRSCheck;
    private javax.swing.JLabel ee;
    private javax.swing.JCheckBox invaliditetCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox jedanRoditeljNezaposlenCheck;
    private javax.swing.JCheckBox korisnikSocijalnePomociCheck;
    private javax.swing.JCheckBox obaRoditeljaNezaposlenaCheck;
    private javax.swing.JTextField skolskaGodinaField;
    private javax.swing.JCheckBox studentiIzViseclanihPorodicaCheck;
    // End of variables declaration//GEN-END:variables
}
